version: 2
jobs:
  deploy:
    docker:
      - image: krzkaczor/circleci-node-aws:latest
    steps:
      - checkout

      - run:
          name: Deploy
          command: |
            ./scripts/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
